In [1]:
import numpy as np
import pandas as pd
import os
import sys
import json

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)


print("Python version:", sys.version)
print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Python version: 3.13.15 (tags/v3.13.15:4061bc4, Aug  5 2026, 13:05:39) [MSC v.1944 64 bit (AMD64)]
Pandas version: 3.0.6
Numpy version: 2.5.3

In [3]:
file_path = "../data/raw/online_retail_II.xlsx"

excel_file = pd.ExcelFile(file_path)

print("Sheets Found:")
print("Sheet names:", excel_file.sheet_names)

Sheets Found:
Sheet names: ['Year 2009-2010', 'Year 2010-2011']

In [4]:
df_2009_2010 = pd.read_excel(
  file_path,
  sheet_name = "Year 2009-2010"
)

df_2010_2011 = pd.read_excel(
  file_path,
  sheet_name = "Year 2010-2011"
)

print("2009-2010:", df_2009_2010.shape)
print("2010-2011:", df_2010_2011.shape)

2009-2010: (525461, 8)
2010-2011: (541910, 8)

In [5]:
retail = pd.concat(
    [df_2009_2010, df_2010_2011],
    ignore_index=True
)

print("Combined dataset shape:", retail.shape)

Combined dataset shape: (1067371, 8)

In [6]:
print(retail.columns.tolist())

['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

In [7]:
retail_raw = retail.copy()

print("Raw backup created.")
print("Rows:", len(retail_raw))

Raw backup created.
Rows: 1067371

In [8]:
retail.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [9]:
retail.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 78.8+ MB

In [10]:
retail.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
Invoice,1067371.0,53628.0,537434.0,1350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockCode,1067371,5305,85123A,5829,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Description,1062989,5698,WHITE HANGING HEART T-LIGHT HOLDER,5918,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,1067371.0,NaN,NaN,NaN,9.938898,-80995.0,1.0,3.0,10.0,80995.0,172.705794
InvoiceDate,1067371,NaN,NaN,NaN,2011-01-02 21:13:55.394029,2009-12-01 07:45:00,2010-07-09 09:46:00,2010-12-07 15:28:00,2011-07-22 10:23:00,2011-12-09 12:50:00,NaN
Price,1067371.0,NaN,NaN,NaN,4.649388,-53594.36,1.25,2.1,4.15,38970.0,123.553059
Customer ID,824364.0,NaN,NaN,NaN,15324.638504,12346.0,13975.0,15255.0,16797.0,18287.0,1697.46445
Country,1067371,43,United Kingdom,981330,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
missing = pd.DataFrame({
    "Missing_Count": retail.isna().sum(),
    "Missing_Percentage": retail.isna().mean() * 100
})

missing = missing.sort_values(
    "Missing_Count",
    ascending=False
)

missing

             Missing_Count  Missing_Percentage
Customer ID         243007           22.766873
Description           4382            0.410541
StockCode                0            0.000000
Invoice                  0            0.000000
Quantity                 0            0.000000
InvoiceDate              0            0.000000
Price                    0            0.000000
Country                  0            0.000000

In [12]:
duplicate_count = retail.duplicated().sum()

print("Duplicate rows:", duplicate_count)
print(
    "Duplicate percentage:",
    round(duplicate_count / len(retail) * 100, 2),
    "%"
)

Duplicate rows: 34335
Duplicate percentage: 3.22 %

In [13]:
retail[retail.duplicated(keep=False)].head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom

In [14]:
print(retail.dtypes)

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

In [15]:
## Convert InvoiceDate to datetime

retail["InvoiceDate"] = pd.to_datetime(
    retail["InvoiceDate"],
    errors="coerce"
)

print(retail["InvoiceDate"].dtype)

datetime64[us]

In [16]:
invalid_dates = retail["InvoiceDate"].isna().sum()

print("Invalid/missing InvoiceDate:", invalid_dates)

Invalid/missing InvoiceDate: 0

In [17]:
text_columns = [
    "Description",
    "Country",
    "StockCode"
]

for col in text_columns:
    retail[col] = retail[col].astype("string").str.strip()

In [18]:
retail[["Description", "Country", "StockCode"]].head()

                           Description         Country StockCode
0  15CM CHRISTMAS GLASS BALL 20 LIGHTS  United Kingdom     85048
1                   PINK CHERRY LIGHTS  United Kingdom    79323P
2                  WHITE CHERRY LIGHTS  United Kingdom    79323W
3          RECORD FRAME 7" SINGLE SIZE  United Kingdom     22041
4       STRAWBERRY CERAMIC TRINKET BOX  United Kingdom     21232

In [20]:
retail["Invoice"] = retail["Invoice"].astype("string").str.strip()

print(retail["Invoice"].head())

0    489434
1    489434
2    489434
3    489434
4    489434
Name: Invoice, dtype: string

In [22]:
retail["IsCancelled"] = (
    retail["Invoice"]
    .str.upper()
    .str.startswith("C")
)

print(
    retail["IsCancelled"].value_counts()
)

IsCancelled
False    1047877
True       19494
Name: count, dtype: Int64

In [23]:
cancelled = retail[retail["IsCancelled"]]

print("Cancelled rows:", len(cancelled))

cancelled.head()

Cancelled rows: 19494

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,IsCancelled
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia,True
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia,True
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia,True
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia,True
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia,True

In [24]:
cancelled["Quantity"].describe()

count    19494.000000
mean       -25.186827
std        805.104908
min     -80995.000000
25%         -6.000000
50%         -2.000000
75%         -1.000000
max          1.000000
Name: Quantity, dtype: float64

In [25]:
## Convert Quantity to numeric
retail["Quantity"] = pd.to_numeric(
    retail["Quantity"],
    errors="coerce"
)

print(retail["Quantity"].dtype)

int64

In [27]:
## Convert UnitPrice to numeric

retail["Price"] = pd.to_numeric(
    retail["Price"],
    errors="coerce"
)
print(retail["Price"].dtype)

float64

In [29]:
## Convert CustomerID to numeric

retail["Customer ID"] = pd.to_numeric(
    retail["Customer ID"],
    errors="coerce"
)

print(retail["Customer ID"].dtype)

float64

In [30]:
print(retail["Quantity"].describe())

count    1.067371e+06
mean     9.938898e+00
std      1.727058e+02
min     -8.099500e+04
25%      1.000000e+00
50%      3.000000e+00
75%      1.000000e+01
max      8.099500e+04
Name: Quantity, dtype: float64

In [31]:
negative_quantity = retail[retail["Quantity"] < 0]

print(
    "Rows with negative quantity:",
    len(negative_quantity)
)

Rows with negative quantity: 22950

In [32]:
zero_quantity = retail[retail["Quantity"] == 0]

print(
    "Rows with zero quantity:",
    len(zero_quantity)
)

Rows with zero quantity: 0

In [33]:
positive_quantity = retail[retail["Quantity"] > 0]

print(
    "Rows with positive quantity:",
    len(positive_quantity)
)

Rows with positive quantity: 1044421

In [35]:
print(retail["Price"].describe())

count    1.067371e+06
mean     4.649388e+00
std      1.235531e+02
min     -5.359436e+04
25%      1.250000e+00
50%      2.100000e+00
75%      4.150000e+00
max      3.897000e+04
Name: Price, dtype: float64

In [36]:
zero_price = retail[retail["Price"] == 0]

print("Rows with zero Price:", len(zero_price))

Rows with zero Price: 6202

In [37]:
negative_price = retail[retail["Price"] < 0]

print("Rows with negative Price:", len(negative_price))

Rows with negative Price: 5

In [38]:
missing_customer = retail["Customer ID"].isna().sum()

print("Missing Customer ID:", missing_customer)
print(
    "Percentage:",
    round(missing_customer / len(retail) * 100, 2),
    "%"
)

Missing Customer ID: 243007
Percentage: 22.77 %

In [39]:
clean = retail.copy()

print("Before basic cleaning:", clean.shape)

Before basic cleaning: (1067371, 9)

In [40]:
clean = clean.dropna(
    subset=["InvoiceDate"]
)

print(
    "After removing invalid dates:",
    clean.shape
)

After removing invalid dates: (1067371, 9)

In [42]:
clean = clean.dropna(
    subset=["Quantity", "Price"]
)

print(
    "After removing invalid numeric values:",
    clean.shape
)

After removing invalid numeric values: (1067371, 9)

In [43]:
before_duplicates = len(clean)

clean = clean.drop_duplicates()

after_duplicates = len(clean)

print("Rows before duplicates removal:", before_duplicates)
print("Rows after duplicates removal:", after_duplicates)
print(
    "Duplicates removed:",
    before_duplicates - after_duplicates
)

Rows before duplicates removal: 1067371
Rows after duplicates removal: 1033036
Duplicates removed: 34335

In [44]:
print(clean.shape)
clean.head()

(1033036, 9)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,IsCancelled
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False

In [45]:
clean.info()

<class 'pandas.DataFrame'>
Index: 1033036 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1033036 non-null  string
 1   StockCode    1033036 non-null  string
 2   Description  1028761 non-null  string
 3   Quantity     1033036 non-null  int64
 4   InvoiceDate  1033036 non-null  datetime64[us]
 5   Price        1033036 non-null  float64
 6   Customer ID  797885 non-null   float64
 7   Country      1033036 non-null  string
 8   IsCancelled  1033036 non-null  boolean
dtypes: boolean(1), datetime64[us](1), float64(2), int64(1), string(4)
memory usage: 123.5 MB

In [46]:
sales = clean[
    (~clean["IsCancelled"]) &
    (clean["Quantity"] > 0) &
    (clean["Price"] > 0) &
    (clean["Customer ID"].notna())
].copy()

In [47]:
print("Sales dataset shape:", sales.shape)

sales.head()

Sales dataset shape: (779425, 9)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,IsCancelled
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False

In [48]:
print(
    "Cancelled transactions remaining:",
    sales["IsCancelled"].sum()
)

Cancelled transactions remaining: 0

In [49]:
print(
    "Minimum quantity:",
    sales["Quantity"].min()
)

Minimum quantity: 1

In [51]:
print(
    "Minimum UnitPrice:",
    sales["Price"].min()
)

Minimum UnitPrice: 0.001

In [53]:
print(
    "Missing Customer ID:",
    sales["Customer ID"].isna().sum()
)

Missing Customer ID: 0

In [54]:
print(
    "Minimum date:",
    sales["InvoiceDate"].min()
)

print(
    "Maximum date:",
    sales["InvoiceDate"].max()
)

Minimum date: 2009-12-01 07:45:00
Maximum date: 2011-12-09 12:50:00

In [56]:
unique_customers = sales["Customer ID"].nunique()

print(
    "Unique customers:",
    unique_customers
)

Unique customers: 5878

In [57]:
unique_products = sales["StockCode"].nunique()

print(
    "Unique products:",
    unique_products
)

Unique products: 4631

In [58]:
unique_countries = sales["Country"].nunique()

print(
    "Unique countries:",
    unique_countries
)

Unique countries: 41

In [60]:
unique_invoices = sales["Invoice"].nunique()

print(
    "Unique invoices:",
    unique_invoices
)

Unique invoices: 36969

In [62]:
quality_report = {
    "raw_rows": int(len(retail_raw)),
    "clean_rows": int(len(clean)),
    "sales_rows": int(len(sales)),
    
    "raw_columns": int(retail_raw.shape[1]),
    "clean_columns": int(clean.shape[1]),
    
    "duplicate_rows_raw": int(retail_raw.duplicated().sum()),
    "duplicate_rows_clean": int(clean.duplicated().sum()),
    
    "missing_customer_id_raw": int(
        retail_raw["Customer ID"].isna().sum()
    ),
    
    "missing_customer_id_sales": int(
        sales["Customer ID"].isna().sum()
    ),
    
    "cancelled_rows": int(
        retail["IsCancelled"].sum()
    ),
    
    "negative_quantity_rows": int(
        (retail["Quantity"] < 0).sum()
    ),
    
    "zero_quantity_rows": int(
        (retail["Quantity"] == 0).sum()
    ),
    
    "zero_price_rows": int(
        (retail["Price"] == 0).sum()
    ),
    
    "unique_customers": int(
        sales["Customer ID"].nunique()
    ),
    
    "unique_products": int(
        sales["StockCode"].nunique()
    ),
    
    "unique_invoices": int(
        sales["Invoice"].nunique()
    ),
    
    "unique_countries": int(
        sales["Country"].nunique()
    ),
    
    "min_date": str(
        sales["InvoiceDate"].min()
    ),
    
    "max_date": str(
        sales["InvoiceDate"].max()
    )
}

quality_report

{'raw_rows': 1067371,
 'clean_rows': 1033036,
 'sales_rows': 779425,
 'raw_columns': 8,
 'clean_columns': 9,
 'duplicate_rows_raw': 34335,
 'duplicate_rows_clean': 0,
 'missing_customer_id_raw': 243007,
 'missing_customer_id_sales': 0,
 'cancelled_rows': 19494,
 'negative_quantity_rows': 22950,
 'zero_quantity_rows': 0,
 'zero_price_rows': 6202,
 'unique_customers': 5878,
 'unique_products': 4631,
 'unique_invoices': 36969,
 'unique_countries': 41,
 'min_date': '2009-12-01 07:45:00',
 'max_date': '2011-12-09 12:50:00'}

In [63]:
output_dir = "../reports/outputs"

os.makedirs(output_dir, exist_ok=True)

report_path = os.path.join(
    output_dir,
    "data_quality_report.json"
)

with open(report_path, "w") as f:
    json.dump(
        quality_report,
        f,
        indent=4
    )

print(
    "Quality report saved:",
    report_path
)

Quality report saved: ../reports/outputs\data_quality_report.json

In [64]:
processed_dir = "../data/processed"

os.makedirs(processed_dir, exist_ok=True)

clean_path = os.path.join(
    processed_dir,
    "retail_clean.csv"
)

clean.to_csv(
    clean_path,
    index=False
)

print(
    "Clean transaction dataset saved:",
    clean_path
)

Clean transaction dataset saved: ../data/processed\retail_clean.csv

In [65]:
sales_path = os.path.join(
    processed_dir,
    "retail_sales.csv"
)

sales.to_csv(
    sales_path,
    index=False
)

print(
    "Sales dataset saved:",
    sales_path
)

Sales dataset saved: ../data/processed\retail_sales.csv

In [66]:
test_sales = pd.read_csv(
    "../data/processed/retail_sales.csv"
)

print("Reloaded shape:", test_sales.shape)

test_sales.head()

Reloaded shape: (779425, 9)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,IsCancelled
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False

In [67]:
test_sales["InvoiceDate"] = pd.to_datetime(
    test_sales["InvoiceDate"],
    errors="coerce"
)

print(test_sales.dtypes)

Invoice                 int64
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
IsCancelled              bool
dtype: object

In [69]:
print("=" * 60)
print("RETAILPULSE DATA CLEANING COMPLETE")
print("=" * 60)

print(f"Raw rows:        {len(retail_raw):,}")
print(f"Clean rows:      {len(clean):,}")
print(f"Sales rows:      {len(sales):,}")

print(f"Customers:       {sales['Customer ID'].nunique():,}")
print(f"Products:        {sales['StockCode'].nunique():,}")
print(f"Invoices:        {sales['Invoice'].nunique():,}")
print(f"Countries:       {sales['Country'].nunique():,}")

print(
    f"Date range:      "
    f"{sales['InvoiceDate'].min().date()} → "
    f"{sales['InvoiceDate'].max().date()}"
)

print(
    f"Missing Customer ID in sales: "
    f"{sales['Customer ID'].isna().sum()}"
)

print(
    f"Cancelled rows in sales: "
    f"{sales['IsCancelled'].sum()}"
)

print("=" * 60)

============================================================
RETAILPULSE DATA CLEANING COMPLETE
============================================================
Raw rows:        1,067,371
Clean rows:      1,033,036
Sales rows:      779,425
Customers:       5,878
Products:        4,631
Invoices:        36,969
Countries:       41
Date range:      2009-12-01 → 2011-12-09
Missing Customer ID in sales: 0
Cancelled rows in sales: 0
============================================================