In [2]:
import numpy as np
import pandas as pd
import os

pd.set_option("display.max_columns", None)

print("Libraries loaded successfully..")

Libraries loaded successfully..

In [3]:
sales = pd.read_csv(
    "../data/processed/retail_sales.csv"
)

sales["InvoiceDate"] = pd.to_datetime(
    sales["InvoiceDate"],
    errors="coerce"
)

print("Shape:", sales.shape)
sales.head()

Shape: (779425, 9)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,IsCancelled
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False

In [4]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 779425 entries, 0 to 779424
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  int64
 1   StockCode    779425 non-null  str
 2   Description  779425 non-null  str
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[us]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  float64
 7   Country      779425 non-null  str
 8   IsCancelled  779425 non-null  bool
dtypes: bool(1), datetime64[us](1), float64(2), int64(2), str(3)
memory usage: 81.7 MB

In [5]:
## Create Revenue

sales["Revenue"] = (
  sales["Quantity"] * 
  sales["Price"]
)

sales[[
  "Quantity",
  "Price",
  "Revenue"
]].head()

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0

In [6]:
print("Minimum revenue:", sales["Revenue"].min())
print("Maximum revenue:", sales["Revenue"].max())

Minimum revenue: 0.001
Maximum revenue: 168469.6

In [7]:
## Create date features

# These will be used by:

# EDA
# forecasting
# Power BI
# Streamlit
# seasonality analysis
# demand analysis

In [8]:
sales["Year"] = sales["InvoiceDate"].dt.year
sales["Month"] = sales["InvoiceDate"].dt.month
sales["MonthName"] = sales["InvoiceDate"].dt.month_name()

sales["Quarter"] = sales["InvoiceDate"].dt.quarter

sales["Day"] = sales["InvoiceDate"].dt.day
sales["DayName"] = sales["InvoiceDate"].dt.day_name()

sales["DayOfWeek"] = sales["InvoiceDate"].dt.dayofweek

sales["WeekOfYear"] = (
    sales["InvoiceDate"]
    .dt.isocalendar()
    .week
    .astype(int)
)

sales["Date"] = sales["InvoiceDate"].dt.date

sales.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,IsCancelled,Revenue,Year,Month,MonthName,Quarter,Day,DayName,DayOfWeek,WeekOfYear,Date
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False,83.4,2009,12,December,4,1,Tuesday,1,49,2009-12-01
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,81.0,2009,12,December,4,1,Tuesday,1,49,2009-12-01
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,81.0,2009,12,December,4,1,Tuesday,1,49,2009-12-01
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False,100.8,2009,12,December,4,1,Tuesday,1,49,2009-12-01
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False,30.0,2009,12,December,4,1,Tuesday,1,49,2009-12-01

In [9]:
sales["Hour"] = sales["InvoiceDate"].dt.hour

sales["IsWeekend"] = (
    sales["DayOfWeek"] >= 5
).astype(int)

sales["IsWeekday"] = (
    sales["DayOfWeek"] < 5
).astype(int)

In [10]:
sales[
    [
        "InvoiceDate",
        "Year",
        "Month",
        "Quarter",
        "DayName",
        "Hour",
        "IsWeekend"
    ]
].head(10)

          InvoiceDate  Year  Month  Quarter  DayName  Hour  IsWeekend
0 2009-12-01 07:45:00  2009     12        4  Tuesday     7          0
1 2009-12-01 07:45:00  2009     12        4  Tuesday     7          0
2 2009-12-01 07:45:00  2009     12        4  Tuesday     7          0
3 2009-12-01 07:45:00  2009     12        4  Tuesday     7          0
4 2009-12-01 07:45:00  2009     12        4  Tuesday     7          0
5 2009-12-01 07:45:00  2009     12        4  Tuesday     7          0
6 2009-12-01 07:45:00  2009     12        4  Tuesday     7          0
7 2009-12-01 07:45:00  2009     12        4  Tuesday     7          0
8 2009-12-01 07:46:00  2009     12        4  Tuesday     7          0
9 2009-12-01 07:46:00  2009     12        4  Tuesday     7          0

In [11]:
## Create Year-Month

sales["YearMonth"] = (
    sales["InvoiceDate"]
    .dt.to_period("M")
    .astype(str)
)

sales[[
    "InvoiceDate",
    "YearMonth"
]].head()

          InvoiceDate YearMonth
0 2009-12-01 07:45:00   2009-12
1 2009-12-01 07:45:00   2009-12
2 2009-12-01 07:45:00   2009-12
3 2009-12-01 07:45:00   2009-12
4 2009-12-01 07:45:00   2009-12

In [12]:
## Create week start

sales["WeekStart"] = (
    sales["InvoiceDate"]
    .dt.to_period("W")
    .apply(lambda x: x.start_time)
)

sales[[
    "InvoiceDate",
    "WeekStart"
]].head()

          InvoiceDate  WeekStart
0 2009-12-01 07:45:00 2009-11-30
1 2009-12-01 07:45:00 2009-11-30
2 2009-12-01 07:45:00 2009-11-30
3 2009-12-01 07:45:00 2009-11-30
4 2009-12-01 07:45:00 2009-11-30

In [13]:
## create month satrt

sales["MonthStart"] = (
    sales["InvoiceDate"]
    .dt.to_period("M")
    .apply(lambda x: x.start_time)
)

sales[[
    "InvoiceDate",
    "MonthStart"
]].head()

          InvoiceDate MonthStart
0 2009-12-01 07:45:00 2009-12-01
1 2009-12-01 07:45:00 2009-12-01
2 2009-12-01 07:45:00 2009-12-01
3 2009-12-01 07:45:00 2009-12-01
4 2009-12-01 07:45:00 2009-12-01

In [16]:
## Invoice-level features


invoice_features = (
    sales.groupby("Invoice")
    .agg(
        InvoiceQuantity=("Quantity", "sum"),
        InvoiceRevenue=("Revenue", "sum"),
        InvoiceItems=("StockCode", "nunique"),
        InvoiceCustomers=("Customer ID", "nunique")
    )
    .reset_index()
)

invoice_features.head()

   Invoice  InvoiceQuantity  InvoiceRevenue  InvoiceItems  InvoiceCustomers
0   489434              166          505.30             8                 1
1   489435               60          145.80             4                 1
2   489436              193          630.33            19                 1
3   489437              145          310.75            23                 1
4   489438              826         2286.24            17                 1

In [18]:
## Add invoice features back to transactions

sales = sales.merge(
    invoice_features,
    on="Invoice",
    how="left"
)

sales.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,IsCancelled,Revenue,Year,Month,MonthName,Quarter,Day,DayName,DayOfWeek,WeekOfYear,Date,Hour,IsWeekend,IsWeekday,YearMonth,WeekStart,MonthStart,InvoiceQuantity,InvoiceRevenue,InvoiceItems,InvoiceCustomers
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False,83.4,2009,12,December,4,1,Tuesday,1,49,2009-12-01,7,0,1,2009-12,2009-11-30,2009-12-01,166,505.3,8,1
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,81.0,2009,12,December,4,1,Tuesday,1,49,2009-12-01,7,0,1,2009-12,2009-11-30,2009-12-01,166,505.3,8,1
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,81.0,2009,12,December,4,1,Tuesday,1,49,2009-12-01,7,0,1,2009-12,2009-11-30,2009-12-01,166,505.3,8,1
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False,100.8,2009,12,December,4,1,Tuesday,1,49,2009-12-01,7,0,1,2009-12,2009-11-30,2009-12-01,166,505.3,8,1
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False,30.0,2009,12,December,4,1,Tuesday,1,49,2009-12-01,7,0,1,2009-12,2009-11-30,2009-12-01,166,505.3,8,1

In [19]:
## Customer-level features

# Now we create customer behavior features.

# These will later be used for:

# RFM
# customer segmentation
# churn prediction
# # customer dashboard

In [20]:
customer_features = (
    sales.groupby("Customer ID")
    .agg(
        CustomerRevenue=("Revenue", "sum"),
        CustomerQuantity=("Quantity", "sum"),
        CustomerOrders=("Invoice", "nunique"),
        CustomerProducts=("StockCode", "nunique"),
        CustomerCountries=("Country", "nunique"),
        FirstPurchase=("InvoiceDate", "min"),
        LastPurchase=("InvoiceDate", "max")
    )
    .reset_index()
)

customer_features.head()

,Customer ID,CustomerRevenue,CustomerQuantity,CustomerOrders,CustomerProducts,CustomerCountries,FirstPurchase,LastPurchase
0,12346.0,77556.46,74285,12,27,1,2009-12-14 08:34:00,2011-01-18 10:01:00
1,12347.0,4921.53,2967,8,126,1,2010-10-31 14:20:00,2011-12-07 15:52:00
2,12348.0,2019.40,2714,5,25,1,2010-09-27 14:59:00,2011-09-25 13:13:00
3,12349.0,4428.69,1624,4,138,1,2010-04-29 13:20:00,2011-11-21 09:51:00
4,12350.0,334.40,197,1,17,1,2011-02-02 16:01:00,2011-02-02 16:01:00

In [23]:
##  Calculate average order value

# Average Order Value =
# Customer Revenue / Customer Orders


customer_features["AverageOrderValue"] = (
    customer_features["CustomerRevenue"] /
    customer_features["CustomerOrders"]
)

customer_features.head()

,Customer ID,CustomerRevenue,CustomerQuantity,CustomerOrders,CustomerProducts,CustomerCountries,FirstPurchase,LastPurchase,AverageOrderValue
0,12346.0,77556.46,74285,12,27,1,2009-12-14 08:34:00,2011-01-18 10:01:00,6463.038333
1,12347.0,4921.53,2967,8,126,1,2010-10-31 14:20:00,2011-12-07 15:52:00,615.191250
2,12348.0,2019.40,2714,5,25,1,2010-09-27 14:59:00,2011-09-25 13:13:00,403.880000
3,12349.0,4428.69,1624,4,138,1,2010-04-29 13:20:00,2011-11-21 09:51:00,1107.172500
4,12350.0,334.40,197,1,17,1,2011-02-02 16:01:00,2011-02-02 16:01:00,334.400000

In [24]:
## Calculate customer lifetime days

customer_features["CustomerLifetimeDays"] = (
    customer_features["LastPurchase"] -
    customer_features["FirstPurchase"]
).dt.days

customer_features.head()

,Customer ID,CustomerRevenue,CustomerQuantity,CustomerOrders,CustomerProducts,CustomerCountries,FirstPurchase,LastPurchase,AverageOrderValue,CustomerLifetimeDays
0,12346.0,77556.46,74285,12,27,1,2009-12-14 08:34:00,2011-01-18 10:01:00,6463.038333,400
1,12347.0,4921.53,2967,8,126,1,2010-10-31 14:20:00,2011-12-07 15:52:00,615.191250,402
2,12348.0,2019.40,2714,5,25,1,2010-09-27 14:59:00,2011-09-25 13:13:00,403.880000,362
3,12349.0,4428.69,1624,4,138,1,2010-04-29 13:20:00,2011-11-21 09:51:00,1107.172500,570
4,12350.0,334.40,197,1,17,1,2011-02-02 16:01:00,2011-02-02 16:01:00,334.400000,0

In [25]:
## Customer purchase frequency

customer_features["OrdersPerLifetimeDay"] = (
    customer_features["CustomerOrders"] /
    customer_features["CustomerLifetimeDays"].replace(0, np.nan)
)

customer_features["OrdersPerLifetimeDay"] = (
    customer_features["OrdersPerLifetimeDay"]
    .fillna(0)
)

In [26]:
## Add customer features to transaction data

sales = sales.merge(
    customer_features,
    on="Customer ID",
    how="left"
)

print(sales.shape)

(779425, 39)

In [28]:
# ## Product-level features

# Now we'll create product-level demand information.

# These will later support:

# product analysis
# demand forecasting
# inventory risk
# dashboard


product_features = (
    sales.groupby("StockCode")
    .agg(
        ProductQuantity=("Quantity", "sum"),
        ProductRevenue=("Revenue", "sum"),
        ProductOrders=("Invoice", "nunique"),
        ProductCustomers=("Customer ID", "nunique"),
        ProductFirstSale=("InvoiceDate", "min"),
        ProductLastSale=("InvoiceDate", "max")
    )
    .reset_index()
)

product_features.head()

,StockCode,ProductQuantity,ProductRevenue,ProductOrders,ProductCustomers,ProductFirstSale,ProductLastSale
0,10002,8479,6638.27,297,164,2009-12-01 09:08:00,2011-04-18 12:56:00
1,10080,303,124.61,26,23,2009-12-02 16:02:00,2011-11-21 17:04:00
2,10109,4,1.68,1,1,2009-12-03 12:31:00,2009-12-03 12:31:00
3,10120,648,136.08,62,52,2009-12-01 16:17:00,2011-12-04 13:15:00
4,10123C,628,226.76,46,39,2009-12-04 15:27:00,2011-03-31 13:14:00

In [29]:
## Calculate product average price

product_avg_price = (
    sales.groupby("StockCode")["Price"]
    .mean()
    .reset_index(name="ProductAveragePrice")
)

product_features = product_features.merge(
    product_avg_price,
    on="StockCode",
    how="left"
)

product_features.head()

,StockCode,ProductQuantity,ProductRevenue,ProductOrders,ProductCustomers,ProductFirstSale,ProductLastSale,ProductAveragePrice
0,10002,8479,6638.27,297,164,2009-12-01 09:08:00,2011-04-18 12:56:00,0.840960
1,10080,303,124.61,26,23,2009-12-02 16:02:00,2011-11-21 17:04:00,0.509259
2,10109,4,1.68,1,1,2009-12-03 12:31:00,2009-12-03 12:31:00,0.420000
3,10120,648,136.08,62,52,2009-12-01 16:17:00,2011-12-04 13:15:00,0.210000
4,10123C,628,226.76,46,39,2009-12-04 15:27:00,2011-03-31 13:14:00,0.621739

In [30]:
## Add product features to sales

sales = sales.merge(
    product_features,
    on="StockCode",
    how="left"
)

print(sales.shape)

(779425, 46)

In [31]:
## Calculate customer revenue percentage

total_revenue = sales["Revenue"].sum()

sales["CustomerRevenueShare"] = (
    sales["CustomerRevenue"] /
    total_revenue
)

print(
    sales["CustomerRevenueShare"].describe()
)

count    7.794250e+05
mean     1.196571e-03
std      3.543932e-03
min      1.697861e-07
25%      9.951134e-05
50%      2.571344e-04
75%      6.551458e-04
max      3.343848e-02
Name: CustomerRevenueShare, dtype: float64

In [32]:
## Calculate product revenue share

sales["ProductRevenueShare"] = (
    sales["ProductRevenue"] /
    total_revenue
)

sales[
    [
        "StockCode",
        "ProductRevenue",
        "ProductRevenueShare"
    ]
].head()

  StockCode  ProductRevenue  ProductRevenueShare
0     85048        18618.75             0.001072
1    79323P        13198.10             0.000760
2    79323W        17384.80             0.001001
3     22041        15088.77             0.000868
4     21232        40994.71             0.002359

In [33]:
## Create daily sales dataset

daily_sales = (
    sales.groupby("Date")
    .agg(
        DailyRevenue=("Revenue", "sum"),
        DailyQuantity=("Quantity", "sum"),
        DailyOrders=("Invoice", "nunique"),
        DailyCustomers=("Customer ID", "nunique"),
        DailyProducts=("StockCode", "nunique")
    )
    .reset_index()
)

daily_sales["Date"] = pd.to_datetime(
    daily_sales["Date"]
)

daily_sales.head()

,Date,DailyRevenue,DailyQuantity,DailyOrders,DailyCustomers,DailyProducts
0,2009-12-01,43894.87,24335,98,91,1042
1,2009-12-02,52762.06,29679,110,94,1087
2,2009-12-03,67413.62,48009,122,106,1082
3,2009-12-04,33913.81,19954,80,76,1006
4,2009-12-05,9803.05,5119,30,26,285

In [34]:
## Add daily time features

daily_sales["Year"] = daily_sales["Date"].dt.year
daily_sales["Month"] = daily_sales["Date"].dt.month
daily_sales["Quarter"] = daily_sales["Date"].dt.quarter
daily_sales["DayOfWeek"] = daily_sales["Date"].dt.dayofweek
daily_sales["WeekOfYear"] = (
    daily_sales["Date"]
    .dt.isocalendar()
    .week
    .astype(int)
)

daily_sales["IsWeekend"] = (
    daily_sales["DayOfWeek"] >= 5
).astype(int)

daily_sales.head()

,Date,DailyRevenue,DailyQuantity,DailyOrders,DailyCustomers,DailyProducts,Year,Month,Quarter,DayOfWeek,WeekOfYear,IsWeekend
0,2009-12-01,43894.87,24335,98,91,1042,2009,12,4,1,49,0
1,2009-12-02,52762.06,29679,110,94,1087,2009,12,4,2,49,0
2,2009-12-03,67413.62,48009,122,106,1082,2009,12,4,3,49,0
3,2009-12-04,33913.81,19954,80,76,1006,2009,12,4,4,49,0
4,2009-12-05,9803.05,5119,30,26,285,2009,12,4,5,49,1

In [35]:
## 7-day rolling average
daily_sales = daily_sales.sort_values("Date")

daily_sales["RevenueRolling7"] = (
    daily_sales["DailyRevenue"]
    .rolling(7)
    .mean()
)

In [36]:
## 14-day rolling average


daily_sales["RevenueRolling14"] = (
    daily_sales["DailyRevenue"]
    .rolling(14)
    .mean()
)

In [37]:
## 30-day rolling average

daily_sales["RevenueRolling30"] = (
    daily_sales["DailyRevenue"]
    .rolling(30)
    .mean()
)

In [ ]:
### Create demand lag features

# Lag features are important for ML-based forecasting.

daily_sales["RevenueLag1"] = (
    daily_sales["DailyRevenue"].shift(1)
)

daily_sales["RevenueLag7"] = (
    daily_sales["DailyRevenue"].shift(7)
)

daily_sales["RevenueLag14"] = (
    daily_sales["DailyRevenue"].shift(14)
)

daily_sales["RevenueLag30"] = (
    daily_sales["DailyRevenue"].shift(30)
)

In [39]:
daily_sales.tail()

,Date,DailyRevenue,DailyQuantity,DailyOrders,DailyCustomers,DailyProducts,Year,Month,Quarter,DayOfWeek,WeekOfYear,IsWeekend,RevenueRolling7,RevenueRolling14,RevenueRolling30,RevenueLag1,RevenueLag7,RevenueLag14,RevenueLag30
599,2011-12-05,58081.09,38347,116,105,1408,2011,12,4,0,49,0,44130.590000,41913.650000,44115.005667,20232.00,16969.25,36606.25,33006.87
600,2011-12-06,45989.66,27736,110,103,1143,2011,12,4,1,49,0,43324.511429,43081.312143,44679.009000,58081.09,51632.21,29642.39,29069.56
601,2011-12-07,69230.60,41011,104,94,1046,2011,12,4,2,49,0,46265.944286,44797.640000,45702.147667,45989.66,48640.57,45202.01,38536.44
602,2011-12-08,50395.96,27476,113,105,1145,2011,12,4,3,49,0,47551.540000,44866.026429,45364.143333,69230.60,41396.79,49438.55,60536.09
603,2011-12-09,184347.66,90553,41,35,457,2011,12,4,4,49,0,67543.295714,52910.662857,49651.849667,50395.96,44405.37,71722.75,55716.47

In [40]:
## Create monthly sales dataset

monthly_sales = (
    sales.groupby("MonthStart")
    .agg(
        MonthlyRevenue=("Revenue", "sum"),
        MonthlyQuantity=("Quantity", "sum"),
        MonthlyOrders=("Invoice", "nunique"),
        MonthlyCustomers=("Customer ID", "nunique"),
        MonthlyProducts=("StockCode", "nunique")
    )
    .reset_index()
)

monthly_sales.head()

,MonthStart,MonthlyRevenue,MonthlyQuantity,MonthlyOrders,MonthlyCustomers,MonthlyProducts
0,2009-12-01,683504.010,398660,1512,955,2725
1,2010-01-01,555802.672,370082,1011,720,2368
2,2010-02-01,504558.956,371861,1104,772,2374
3,2010-03-01,696978.471,502100,1524,1057,2668
4,2010-04-01,591982.002,350587,1329,942,2340

In [41]:
## Monthly growth

monthly_sales["RevenueGrowth"] = (
    monthly_sales["MonthlyRevenue"]
    .pct_change()
)

monthly_sales.head()

,MonthStart,MonthlyRevenue,MonthlyQuantity,MonthlyOrders,MonthlyCustomers,MonthlyProducts,RevenueGrowth
0,2009-12-01,683504.010,398660,1512,955,2725,NaN
1,2010-01-01,555802.672,370082,1011,720,2368,-0.186833
2,2010-02-01,504558.956,371861,1104,772,2374,-0.092198
3,2010-03-01,696978.471,502100,1524,1057,2668,0.381362
4,2010-04-01,591982.002,350587,1329,942,2340,-0.150645

In [42]:
## Product daily demand

# For inventory and demand forecasting, we also need product-level daily demand.

product_daily = (
    sales.groupby(
        ["Date", "StockCode"]
    )
    .agg(
        QuantitySold=("Quantity", "sum"),
        Revenue=("Revenue", "sum"),
        Orders=("Invoice", "nunique"),
        Customers=("Customer ID", "nunique")
    )
    .reset_index()
)

product_daily["Date"] = pd.to_datetime(
    product_daily["Date"]
)

product_daily.head()

        Date StockCode  QuantitySold  Revenue  Orders  Customers
0 2009-12-01     10002            12    10.20       1          1
1 2009-12-01     10120            60    12.60       1          1
2 2009-12-01     10125             4     3.40       1          1
3 2009-12-01     10133             6     5.10       1          1
4 2009-12-01     10135            17    21.25       3          3

In [43]:
## Product demand rolling average

product_daily = product_daily.sort_values(
    ["StockCode", "Date"]
)

product_daily["DemandRolling7"] = (
    product_daily
    .groupby("StockCode")["QuantitySold"]
    .transform(
        lambda x: x.rolling(7, min_periods=1).mean()
    )
)

product_daily["DemandRolling30"] = (
    product_daily
    .groupby("StockCode")["QuantitySold"]
    .transform(
        lambda x: x.rolling(30, min_periods=1).mean()
    )
)

product_daily.head()

,Date,StockCode,QuantitySold,Revenue,Orders,Customers,DemandRolling7,DemandRolling30
0,2009-12-01,10002,12,10.20,1,1,12.000000,12.000000
2129,2009-12-03,10002,6,5.10,3,3,9.000000,9.000000
3211,2009-12-04,10002,73,62.05,4,4,30.333333,30.333333
4502,2009-12-06,10002,49,41.65,2,2,35.000000,35.000000
5463,2009-12-07,10002,2,1.70,1,1,28.400000,28.400000

In [44]:
## Product demand lag


product_daily["DemandLag1"] = (
    product_daily
    .groupby("StockCode")["QuantitySold"]
    .shift(1)
)

product_daily["DemandLag7"] = (
    product_daily
    .groupby("StockCode")["QuantitySold"]
    .shift(7)
)

product_daily.head(10)

,Date,StockCode,QuantitySold,Revenue,Orders,Customers,DemandRolling7,DemandRolling30,DemandLag1,DemandLag7
0,2009-12-01,10002,12,10.20,1,1,12.000000,12.000000,NaN,NaN
2129,2009-12-03,10002,6,5.10,3,3,9.000000,9.000000,12.0,NaN
3211,2009-12-04,10002,73,62.05,4,4,30.333333,30.333333,6.0,NaN
4502,2009-12-06,10002,49,41.65,2,2,35.000000,35.000000,73.0,NaN
5463,2009-12-07,10002,2,1.70,1,1,28.400000,28.400000,49.0,NaN
6390,2009-12-08,10002,12,10.20,1,1,25.666667,25.666667,2.0,NaN
9117,2009-12-11,10002,9,7.65,1,1,23.285714,23.285714,12.0,NaN
10922,2009-12-14,10002,36,30.60,2,2,26.714286,24.875000,9.0,12.0
15793,2009-12-21,10002,12,10.20,1,1,27.571429,23.444444,36.0,6.0
16374,2009-12-23,10002,1,0.85,1,1,17.285714,21.200000,12.0,73.0

In [45]:
## moves unnecessary duplicate columns if any

print("Feature engineered sales shape:", sales.shape)
print("Daily sales shape:", daily_sales.shape)
print("Monthly sales shape:", monthly_sales.shape)
print("Product daily shape:", product_daily.shape)

Feature engineered sales shape: (779425, 48)
Daily sales shape: (604, 19)
Monthly sales shape: (25, 7)
Product daily shape: (439167, 10)

In [46]:
## Save feature-engineered transaction dataset

processed_dir = "../data/processed"

os.makedirs(
    processed_dir,
    exist_ok=True
)

sales.to_csv(
    f"{processed_dir}/feature_engineered_sales.csv",
    index=False
)

print("Saved feature_engineered_sales.csv")

Saved feature_engineered_sales.csv

In [47]:
##  Save daily forecasting dataset

daily_sales.to_csv(
    f"{processed_dir}/daily_sales_features.csv",
    index=False
)

print("Saved daily_sales_features.csv")

Saved daily_sales_features.csv

In [48]:
## Save monthly dataset

monthly_sales.to_csv(
    f"{processed_dir}/monthly_sales_features.csv",
    index=False
)

print("Saved monthly_sales_features.csv")

Saved monthly_sales_features.csv

In [50]:
##  Save product demand dataset

product_daily.to_csv(
    f"{processed_dir}/product_daily_demand.csv",
    index=False
)

print("Saved product_daily_demand.csv")

Saved product_daily_demand.csv

In [51]:
## Save customer features

# This will be directly useful for RFM and churn. 

customer_features.to_csv(
    f"{processed_dir}/customer_features.csv",
    index=False
)

print("Saved customer_features.csv")

Saved customer_features.csv

In [52]:
## Save product features

product_features.to_csv(
    f"{processed_dir}/product_features.csv",
    index=False
)

print("Saved product_features.csv")

Saved product_features.csv

In [54]:
## Final validation


print("=" * 70)
print("RETAILPULSE FEATURE ENGINEERING COMPLETE")
print("=" * 70)

print(f"Transaction rows:  {len(sales):,}")
print(f"Transaction cols:  {sales.shape[1]:,}")

print(f"Customers:          {sales['Customer ID'].nunique():,}")
print(f"Products:           {sales['StockCode'].nunique():,}")
print(f"Invoices:           {sales['Invoice'].nunique():,}")

print(f"Total Revenue:      {sales['Revenue'].sum():,.2f}")

print(f"Daily rows:         {len(daily_sales):,}")
print(f"Monthly rows:       {len(monthly_sales):,}")
print(f"Product-day rows:   {len(product_daily):,}")

print("=" * 70)

======================================================================
RETAILPULSE FEATURE ENGINEERING COMPLETE
======================================================================
Transaction rows:  779,425
Transaction cols:  48
Customers:          5,878
Products:           4,631
Invoices:           36,969
Total Revenue:      17,374,804.27
Daily rows:         604
Monthly rows:       25
Product-day rows:   439,167
======================================================================

In [55]:
sales.columns.tolist()

['Invoice',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'Price',
 'Customer ID',
 'Country',
 'IsCancelled',
 'Revenue',
 'Year',
 'Month',
 'MonthName',
 'Quarter',
 'Day',
 'DayName',
 'DayOfWeek',
 'WeekOfYear',
 'Date',
 'Hour',
 'IsWeekend',
 'IsWeekday',
 'YearMonth',
 'WeekStart',
 'MonthStart',
 'InvoiceQuantity',
 'InvoiceRevenue',
 'InvoiceItems',
 'InvoiceCustomers',
 'CustomerRevenue',
 'CustomerQuantity',
 'CustomerOrders',
 'CustomerProducts',
 'CustomerCountries',
 'FirstPurchase',
 'LastPurchase',
 'AverageOrderValue',
 'CustomerLifetimeDays',
 'OrdersPerLifetimeDay',
 'ProductQuantity',
 'ProductRevenue',
 'ProductOrders',
 'ProductCustomers',
 'ProductFirstSale',
 'ProductLastSale',
 'ProductAveragePrice',
 'CustomerRevenueShare',
 'ProductRevenueShare']